#!/usr/bin/env python
import cgi
import cgitb
import os
import datetime
import socket

cgitb.enable()



default = "No Value Present"


print("Content-Type: text/html")
print("")

today = datetime.date.today()
body = """<html>
<head>
<title>Lab 1 - CGI experiments</title>
</head>
<body>
<p>Hey there, this page has been generated by {software}, running {script}</p>
<p>Today is {month} {date}, {year}.</p>
<p>This page was requested by IP Address {client_ip}</p>
</body>
</html>""".format(
    software=os.environ.get('SERVER_SOFTWARE', default),
    script=os.path.realpath(__file__),
    month=datetime.date.today().strftime('%B'),
    date=today.day,
    year=today.year,
    client_ip=socket.gethostbyname(socket.gethostname())
)
print(body)
